# Generated by Django 5.2.3 on 2025-06-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actvio'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
