# Generated by Django 5.0.3 on 2025-06-14 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
